### PR TITLE
Docker api

### PR DESCRIPTION
**Pull request by dluman**
Several improvements to stop container double-starting and streamlining how the hub works. Namely, we've transitioned to using the `dockerode` interface to the _actual Docker API_, rather than trying to hold onto that data ourselves. This is much more reliable than a flimsy data structure created at runtime.

We still need to store the `lastActive` time of user container interaction.

### CODE REVIEW

**Review by ullrichd21 — DISMISSED** [review]
Looks like a solid improvement. Lets hope it's a bit more stable.

**Comment by dluman** [comment]
The previous commit institutes a _very crude_ queuing system that waits for containers to fully start before redirecting back to `/login` for final boot-over. I'm running this in parallel on `cdr` and `world`, but I'd like another look. I tested with independent browsers and accounts. It seems to function OK.

**Comment by ullrichd21** [comment]
cdr gives me a 502, and world logged in to a white page, that's it. On firefox.

**Comment by dluman** [comment]
This version requires cookie deletion and re-establishment of sessions; it's unavoidable, I'm afraid.

**Pull request merged**
